### PR TITLE
Job 312

### PR DESCRIPTION
**Pull request by Ferenc-**

### CODE REVIEW

**Review by pvital — APPROVED** [review]
LGTM

**Review by GSVarsha — COMMENTED** [review]
Should we implement [the tearDown method](https://github.com/instana/python-sensor/pull/459/files#diff-538f103ff7ceb13bb41f19a3b6f24615d28daf49b120298e928f998a98b7b4a7L36-L37) to release the resources? (pymongo connection)

**Comment by GSVarsha** [comment]
Can we move [this](https://github.com/instana/python-sensor/pull/459/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128L36) import statement to the beginning of the file just to be consistent?

**Comment by GSVarsha** [comment]
Is [this](https://github.com/instana/python-sensor/blob/job-312/tests/opentracing/test_ot_propagators.py#L31) relevant anymore provided that we've removed `nosetests` from our code?

**Comment by Ferenc-** [comment]
> Should we implement [the tearDown method](https://github.com/instana/python-sensor/pull/459/files#diff-538f103ff7ceb13bb41f19a3b6f24615d28daf49b120298e928f998a98b7b4a7L36-L37) to release the resources? (pymongo connection)

Done

**Comment by Ferenc-** [comment]
> Can we move [this](https://github.com/instana/python-sensor/pull/459/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128L36) import statement to the beginning of the file just to be consistent?

For obvisous reasons it can't overtake the environment variable settings, and it's dependent import, but I have moved it to the beginning as much as possible.

**Comment by Ferenc-** [comment]
> Is [this](https://github.com/instana/python-sensor/blob/job-312/tests/opentracing/test_ot_propagators.py#L31) relevant anymore provided that we've removed `nosetests` from our code?

Renamed.

**Review by GSVarsha — APPROVED** [review]
Looks good to me!

**Pull request merged**
